GET http://localhost:3001
Content-Type: 'application/json'

###

POST http://localhost:3001/api/user/register
Content-Type: application/json

{
    "email": "try@example.com",
    "password": "password123"
}

###

PUT http://localhost:3001/api/user/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2UxNWRjZTQ3MTQ0NWQxNTZmMTRiNGEiLCJpYXQiOjE3NDI4MjI4NjIsImV4cCI6MTc0MjkwOTI2Mn0.vE5k--yS4Geu2SkzxhUVtL4FhK5JXN5noD56v_XJYpY

{
    "code": "438843"
}

###

POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "try@example.com",
    "password": "password123"
}

###